name: Desplegar Nginx en EKS

on:
  push:
    branches:
      - main

jobs:
  deploy-to-eks:
    runs-on: self-hosted
    permissions:
      id-token: write   # Permiso para solicitar un token OIDC de GitHub
      contents: read 
      
    steps:
    - name: 1. Checkout del código
      uses: actions/checkout@v4

    - name: 2. Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::730335621500:role/test-cluster-gh-runners-iam-role
        aws-region: us-east-1

    - name: 3. Desplegar Nginx en EKS
      run: |
        echo "Instalando AWS CLI y kubectl..."
        
        # Instalar AWS CLI v2
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
        rm -rf awscliv2.zip aws

        # Instalar kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        rm kubectl
        
        echo "Configurando kubectl..."
        aws eks update-kubeconfig --name test-cluster --region us-east-1

        echo "Desplegando manifiesto de Nginx..."
        kubectl apply -f nginx-deployment.yaml
        echo "Consultando pods y servicios..."
        kubectl get po -A
        
        echo "¡Despliegue completado!"
